namespace FCon.Core.Localization;

/// <summary>Strings built in code: statuses, dialogs, tray, computed labels.</summary>
public static partial class Strings
{
    private static readonly Dictionary<string, string> CodeEn = new(StringComparer.Ordinal)
    {
        // connection status
        ["Status_Connected"] = "Connected",
        ["Status_Unstable"] = "Unstable",
        ["Status_Connecting"] = "Connecting",
        ["Status_Verifying"] = "Verifying",
        ["Status_Recovering"] = "Recovering",
        ["Status_Failed"] = "Failed",
        ["Status_Disconnected"] = "Disconnected",
        ["Btn_Disconnect"] = "Disconnect",
        ["Btn_StopConnecting"] = "Stop connecting",
        ["Btn_StopVerifying"] = "Stop verifying",
        ["Btn_StopReconnecting"] = "Stop reconnecting",
        ["Quality_HealthyMs"] = "Healthy · {0} ms",
        ["Quality_Healthy"] = "Healthy",
        ["Quality_NotConnected"] = "Not connected",
        ["NoServerSelected"] = "No server selected",
        ["ExitUnknown"] = "exit unknown",
        ["CountersNeedSingBox"] = "counters need sing-box",
        ["ThisSession"] = "{0} this session",
        ["ConnCount"] = "{0} conn",
        ["NewServer"] = "New server",

        // servers page dialogs
        ["Dlg_NoServers"] = "No servers",
        ["Dlg_NoServersBody"] = "Add a server or import a subscription first.",
        ["Dlg_NotUsable"] = "This server is not usable",
        ["Dlg_DeleteServers"] = "Delete servers",
        ["Dlg_DeleteOne"] = "this server",
        ["Dlg_DeleteMany"] = "these {0} servers",
        ["Dlg_DeleteBody"] = "Remove {0} from the list?",
        ["Dlg_NothingToImport"] = "Nothing to import",
        ["Dlg_ClipboardEmpty"] = "The clipboard does not contain any text.",
        ["Dlg_ImportFailed"] = "Import failed",
        ["Dlg_NoLinks"] = "No recognisable server links were found.",
        ["ImportedCount"] = "Imported {0} server(s).",
        ["SkippedCount"] = "Skipped {0}:",
        ["Dlg_ImportComplete"] = "Import complete",
        ["Dlg_CannotGenerate"] = "Cannot generate configuration",
        ["Dlg_RemoveDuplicates"] = "Remove duplicates",
        ["NoDuplicates"] = "No duplicate servers were found.",
        ["RemovedDuplicates"] = "Removed {0} duplicate server(s).",
        ["Testing"] = "Testing {0}/{1}",
        ["TestingReal"] = " (real requests)",
        ["TestingHandshake"] = " (handshake)",
        ["Dlg_NotConnected"] = "Not connected",
        ["ConnectFirstLatency"] = "Connect first to measure latency through the tunnel.",
        ["MeasuringDelay"] = "Measuring real delay...",
        ["RealDelayResult"] = "{0}: {1} ms through the tunnel.",
        ["ConnectFirstSpeed"] = "Connect first to measure speed.",
        ["MeasuringThroughput"] = "Measuring throughput...",
        ["NoDataCame"] = "{0}: no data came through.",
        ["SpeedResult"] = "{0}: {1} Mbit/s down ({2} MB/s).",
        ["ConfigTitle"] = "{0} config — {1}",

        // settings page
        ["Dlg_DisconnectToUpdate"] = "Disconnect to update?",
        ["DisconnectToUpdateBody"] = "{0} is in use by the current connection. Disconnect and replace it?",
        ["Dlg_CoreInstalled"] = "Core installed",
        ["Dlg_CoreInstallFailed"] = "Could not install the core",
        ["Dlg_DownloadCore"] = "Download the core",
        ["Dlg_InstallCore"] = "Install the core",
        ["InstallCoreBody"] = "Download the Windows amd64 archive, then copy the executable into:\n\n{0}\n\nThen press \"Re-check\".",
        ["Dlg_Optimise"] = "Optimise settings",
        ["NothingLeftToFix"] = "Nothing left to fix automatically. Anything still listed needs a decision only you can make, such as changing a server's cipher.",
        ["Applied"] = "Applied:",
        ["Dlg_PortsUpdated"] = "Ports updated",
        ["PortsUpdatedBody"] = "SOCKS {0}, HTTP {1}, API {2}. Reconnect to apply.",
        ["Dlg_SystemProxy"] = "System proxy",
        ["ProxyRestored"] = "The Windows proxy settings were restored.",
        ["NoProblems"] = "No problems found.",
        ["SeriousAndWarnings"] = "{0} serious issue(s), {1} warning(s)",
        ["WarningsCount"] = "{0} warning(s)",
        ["Suggestions"] = "{0} suggestion(s)",
        ["Plugin_Loaded"] = "loaded",
        ["Starting"] = "Starting...",
        ["Language"] = "Language",
        ["Lang_System"] = "Follow Windows",

        // engine rows
        ["Engine_NotInstalled"] = "Not installed",
        ["Engine_TooOld"] = "Too old",
        ["Engine_PreRelease"] = "Pre-release",
        ["Engine_Ready"] = "Ready",
        ["Engine_DetailNotInstalled"] = "Download the latest stable release, or put {0} in {1}",
        ["Engine_DetailTooOld"] = "{0} is older than {1}; update it. {2}",
        ["Engine_DetailPreRelease"] = "{0} is a pre-release; a stable build is recommended. {1}",
        ["Engine_Update"] = "Update",
        ["Engine_Download"] = "Download",

        // subscriptions
        ["AddSubscriptionBody"] = "Paste the subscription URL. It will be fetched and its servers imported.",
        ["Dlg_InvalidUrl"] = "Invalid URL",
        ["InvalidUrlBody"] = "A subscription URL must start with http:// or https://.",
        ["Dlg_RenameSubscription"] = "Rename subscription",
        ["DisplayName"] = "Display name",
        ["Dlg_BuiltIn"] = "Built-in subscription",
        ["BuiltInFixedUrl"] = "This list ships with KVN and its address is fixed. Add your own subscription for a different URL.",
        ["Dlg_SubscriptionUrl"] = "Subscription URL",
        ["UpdateFetchUrl"] = "Update the fetch URL",
        ["BuiltInCannotRemove"] = "This list ships with KVN and cannot be removed. Uncheck it to take its servers out of use.",
        ["Dlg_RemoveSubscription"] = "Remove subscription",
        ["RemoveSubscriptionBody"] = "Remove \"{0}\" and the {1} server(s) it provided?",
        ["Updating"] = "Updating {0}...",
        ["Dlg_UpdateFailed"] = "Subscription update failed",
        ["Dlg_SomeFailed"] = "Some subscriptions failed",
        ["Never"] = "never",
        ["Deactivated"] = "Deactivated",
        ["QuotaOf"] = "{0} of {1}",
        ["Expires"] = "expires {0}",

        // routing
        ["NewRule"] = "New rule",
        ["Dlg_ResetRouting"] = "Reset routing",
        ["ResetRoutingBody"] = "Discard all rules and restore the defaults?",
        ["DomainsCount"] = "{0} domain(s)",
        ["IpRulesCount"] = "{0} IP rule(s)",
        ["PortsList"] = "ports {0}",
        ["ProcessesCount"] = "{0} process(es)",
        ["MatchesNothing"] = "matches nothing yet",

        // server rows
        ["Row_Timeout"] = "timeout",
        ["Row_Resting"] = "resting",
        ["Row_Fail"] = "{0} fail",
        ["Row_Untried"] = "untried",
        ["Row_Reliable"] = "reliable",
        ["Row_NoRecord"] = "No record yet. Filled in once this server has actually carried traffic.",
        ["Row_OkFailed"] = "{0} ok, {1} failed",
        ["Row_Typical"] = "{0} ms typical",
        ["Row_Jitter"] = "{0} ms jitter",
        ["Row_RestingAfter"] = "resting after repeated failures",
        ["Row_LastError"] = "last error: {0}",

        // editor
        ["Editor_AddServer"] = "Add server",
        ["Editor_EditServer"] = "Edit server",
        ["Editor_LinkNotParsed"] = "Link could not be parsed.",
        ["Editor_ReadyToSave"] = "Ready to save.",
        ["Editor_FixFirst"] = "Fix these first",

        // tray and dialogs
        ["Tray_ShowWindow"] = "Show window",
        ["Tray_Exit"] = "Exit",
        ["Tray_ConnectedTo"] = "Connected — {0}",
        ["Tray_Connecting"] = "Connecting...",
        ["Tray_Stopping"] = "Stopping...",
        // diagnostics
        ["Diagnose"] = "Diagnose",
        ["Diagnose_tip"] = "Check the core, the internet, DNS, a direct socket to the server, the tunnel and Windows Firewall, and say which one fails.",
        ["Diagnosing"] = "Diagnosing...",
        ["Dlg_Diagnostics"] = "Connection diagnostics",
        ["Dlg_AllowFirewall"] = "Allow through Windows Firewall?",
        ["AllowFirewallBody"] = "Windows refused an outgoing connection, or the firewall is set to block programs without a rule. Add allow rules for KVN and the proxy core? Windows will ask for administrator approval.",
        ["FirewallRulesAdded"] = "Rules added. Try connecting again.",
        ["FirewallRulesFailed"] = "No rules were added. The prompt was declined, or netsh failed. You can add them in Windows Security → Firewall → Allow an app.",
        ["Diag_Core"] = "Proxy core",
        ["Diag_CoreMissing"] = "{0} is not installed",
        ["Diag_CoreMissingHint"] = "Settings → Download, or put the executable in the engines folder.",
        ["Diag_Internet"] = "Direct internet",
        ["Diag_InternetOk"] = "reachable without a proxy",
        ["Diag_InternetHint"] = "This machine cannot reach the test URL on its own. Check Wi-Fi/Ethernet, or the URL may be blocked on this network.",
        ["Diag_AccessDeniedHint"] = "Windows refused the connection (WSAEACCES). A firewall or security product blocks this program. Add an allow rule for KVN and the core.",
        ["Diag_Server"] = "Server",
        ["Diag_NoServer"] = "no server selected; add or select one to test reachability",
        ["Diag_Dns"] = "Server name",
        ["Diag_DnsLiteral"] = "{0} is an IP address; no lookup needed",
        ["Diag_DnsResolved"] = "{0} resolves to {1}",
        ["Diag_DnsEmpty"] = "{0} resolved to no addresses",
        ["Diag_DnsFailed"] = "{0} could not be resolved ({1})",
        ["Diag_DnsHint"] = "The system resolver cannot find the server name. Check the link, or try a different DNS in Windows network settings.",
        ["Diag_Reach"] = "Reach the server",
        ["Diag_ReachUdp"] = "{0} uses UDP; a TCP probe cannot test it. If everything else passes, the ISP may be dropping UDP.",
        ["Diag_ReachOk"] = "{0} accepted a connection in {1} ms",
        ["Diag_ReachDenied"] = "Windows refused to open a connection to {0}",
        ["Diag_ReachTimeout"] = "{0} did not answer within 5 s",
        ["Diag_TimeoutHint"] = "No answer at all: the address is blocked upstream, or the server is down. Try another server from the list.",
        ["Diag_ReachRefused"] = "{0} refused the connection",
        ["Diag_RefusedHint"] = "The server is reachable but nothing listens on that port. The link's port may be wrong or the service stopped.",
        ["Diag_ReachNoRoute"] = "no route to {0}",
        ["Diag_NoRouteHint"] = "The network has no path to that address. Often a VPN adapter or a bad gateway; check the adapter and try again.",
        ["Diag_ReachReset"] = "{0} reset the connection",
        ["Diag_ResetHint"] = "Something in the path closed the connection at once. Typical of deep packet inspection; try a REALITY or Hysteria 2 server.",
        ["Diag_ReachOther"] = "{0} failed: {1}",
        ["Diag_Listener"] = "Local listener",
        ["Diag_ListenerOk"] = "core is listening on SOCKS {0} and HTTP {1}",
        ["Diag_ListenerMissing"] = "the core is marked connected but port {0} is not listening",
        ["Diag_ListenerHint"] = "Disconnect and connect again; if it persists, check the Log page for the core's own error.",
        ["Diag_NotConnected"] = "not connected; connect first to test the tunnel itself",
        ["Diag_Tunnel"] = "Through the tunnel",
        ["Diag_TunnelOk"] = "a real request came back in {0} ms",
        ["Diag_TunnelFailed"] = "the request failed: {0}",
        ["Diag_TunnelHint"] = "The core runs but the server does not carry traffic. Wrong credentials, a dead server, or the protocol is blocked. Try another server.",
        ["Diag_Firewall"] = "Windows Firewall",
        ["Diag_FirewallUnknown"] = "could not be queried; it may be disabled, or a third-party firewall is in charge",
        ["Diag_FirewallOff"] = "off for the {0} profile",
        ["Diag_FirewallBlockRules"] = "a rule blocks this program: {0}",
        ["Diag_FirewallDefaultBlock"] = "the {0} profile blocks outgoing connections by default and no rule allows KVN or the core",
        ["Diag_FirewallHint"] = "Use the prompt after this report to add allow rules, or do it in Windows Security → Firewall & network protection.",
        ["Diag_FirewallAllowRules"] = "allowed by {0}",
        ["Diag_FirewallPermissive"] = "on for the {0} profile; outgoing connections are allowed by default",
        ["Diag_SystemProxy"] = "Windows proxy",
        ["Diag_SystemProxyIs"] = "set to {0}",
        ["Diag_SystemProxyOff"] = "not set",
        ["Diag_SystemProxyHint"] = "Connected, but Windows is not pointed at KVN's listener. Reconnect, or check Settings → Traffic capture.",
        // missing core
        ["Dlg_NoCore"] = "Proxy core needed",
        ["NoCoreBody"] = "KVN cannot connect without a proxy core. Download the latest stable {0} now? The archive is checked against its published checksum before it is installed.",
        ["NoCore_Banner"] = "No proxy core is installed: {0} was not found. Nothing can connect until it is in place.",
        ["NoCore_Download"] = "Download {0}",
        ["Msg_Yes"] = "Yes",
        ["Msg_No"] = "No",
        ["Crash"] = "KVN hit an unexpected error",
    };
}
