namespace FCon.Core.Localization;

/// <summary>Strings built in code: statuses, dialogs, tray, computed labels.</summary>
public static partial class Strings
{
    private static readonly Dictionary<string, string> CodeEn = new(StringComparer.Ordinal)
    {
        // connection status
        ["Status_Connected"] = "Connected",
        ["Status_Unstable"] = "Unstable",
        ["Status_Connecting"] = "Connecting",
        ["Status_Verifying"] = "Verifying",
        ["Status_Recovering"] = "Recovering",
        ["Status_Failed"] = "Failed",
        ["Status_Disconnected"] = "Disconnected",
        ["Btn_Disconnect"] = "Disconnect",
        ["Btn_StopConnecting"] = "Stop connecting",
        ["Btn_StopVerifying"] = "Stop verifying",
        ["Btn_StopReconnecting"] = "Stop reconnecting",
        ["Quality_HealthyMs"] = "Healthy · {0} ms",
        ["Quality_Healthy"] = "Healthy",
        ["Quality_NotConnected"] = "Not connected",
        ["NoServerSelected"] = "No server selected",
        ["ExitUnknown"] = "exit unknown",
        ["CountersNeedSingBox"] = "counters need sing-box",
        ["ThisSession"] = "{0} this session",
        ["ConnCount"] = "{0} conn",
        ["NewServer"] = "New server",

        // servers page dialogs
        ["Dlg_NoServers"] = "No servers",
        ["Dlg_NoServersBody"] = "Add a server or import a subscription first.",
        ["Dlg_NotUsable"] = "This server is not usable",
        ["Dlg_DeleteServers"] = "Delete servers",
        ["Dlg_DeleteOne"] = "this server",
        ["Dlg_DeleteMany"] = "these {0} servers",
        ["Dlg_DeleteBody"] = "Remove {0} from the list?",
        ["Dlg_NothingToImport"] = "Nothing to import",
        ["Dlg_ClipboardEmpty"] = "The clipboard does not contain any text.",
        ["Dlg_ImportFailed"] = "Import failed",
        ["Dlg_NoLinks"] = "No recognisable server links were found.",
        ["ImportedCount"] = "Imported {0} server(s).",
        ["SkippedCount"] = "Skipped {0}:",
        ["Dlg_ImportComplete"] = "Import complete",
        ["Dlg_CannotGenerate"] = "Cannot generate configuration",
        ["Dlg_RemoveDuplicates"] = "Remove duplicates",
        ["NoDuplicates"] = "No duplicate servers were found.",
        ["RemovedDuplicates"] = "Removed {0} duplicate server(s).",
        ["Testing"] = "Testing {0}/{1}",
        ["TestingReal"] = " (real requests)",
        ["TestingHandshake"] = " (handshake)",
        ["Dlg_NotConnected"] = "Not connected",
        ["ConnectFirstLatency"] = "Connect first to measure latency through the tunnel.",
        ["MeasuringDelay"] = "Measuring real delay...",
        ["RealDelayResult"] = "{0}: {1} ms through the tunnel.",
        ["ConnectFirstSpeed"] = "Connect first to measure speed.",
        ["MeasuringThroughput"] = "Measuring throughput...",
        ["NoDataCame"] = "{0}: no data came through.",
        ["SpeedResult"] = "{0}: {1} Mbit/s down ({2} MB/s).",
        ["ConfigTitle"] = "{0} config — {1}",

        // settings page
        ["Dlg_DisconnectToUpdate"] = "Disconnect to update?",
        ["DisconnectToUpdateBody"] = "{0} is in use by the current connection. Disconnect and replace it?",
        ["Dlg_CoreInstalled"] = "Core installed",
        ["Dlg_CoreInstallFailed"] = "Could not install the core",
        ["Dlg_DownloadCore"] = "Download the core",
        ["Dlg_InstallCore"] = "Install the core",
        ["InstallCoreBody"] = "Download the Windows amd64 archive, then copy the executable into:\n\n{0}\n\nThen press \"Re-check\".",
        ["Dlg_Optimise"] = "Optimise settings",
        ["NothingLeftToFix"] = "Nothing left to fix automatically. Anything still listed needs a decision only you can make, such as changing a server's cipher.",
        ["Applied"] = "Applied:",
        ["Dlg_PortsUpdated"] = "Ports updated",
        ["PortsUpdatedBody"] = "SOCKS {0}, HTTP {1}, API {2}. Reconnect to apply.",
        ["Dlg_SystemProxy"] = "System proxy",
        ["ProxyRestored"] = "The Windows proxy settings were restored.",
        ["NoProblems"] = "No problems found.",
        ["SeriousAndWarnings"] = "{0} serious issue(s), {1} warning(s)",
        ["WarningsCount"] = "{0} warning(s)",
        ["Suggestions"] = "{0} suggestion(s)",
        ["Plugin_Loaded"] = "loaded",
        ["Starting"] = "Starting...",
        ["Language"] = "Language",
        ["Lang_System"] = "Follow Windows",

        // engine rows
        ["Engine_NotInstalled"] = "Not installed",
        ["Engine_TooOld"] = "Too old",
        ["Engine_PreRelease"] = "Pre-release",
        ["Engine_Ready"] = "Ready",
        ["Engine_DetailNotInstalled"] = "Download the latest stable release, or put {0} in {1}",
        ["Engine_DetailTooOld"] = "{0} is older than {1}; update it. {2}",
        ["Engine_DetailPreRelease"] = "{0} is a pre-release; a stable build is recommended. {1}",
        ["Engine_Update"] = "Update",
        ["Engine_Download"] = "Download",

        // subscriptions
        ["AddSubscriptionBody"] = "Paste the subscription URL. It will be fetched and its servers imported.",
        ["Dlg_InvalidUrl"] = "Invalid URL",
        ["InvalidUrlBody"] = "A subscription URL must start with http:// or https://.",
        ["Dlg_RenameSubscription"] = "Rename subscription",
        ["DisplayName"] = "Display name",
        ["Dlg_BuiltIn"] = "Built-in subscription",
        ["BuiltInFixedUrl"] = "This list ships with KVN and its address is fixed. Add your own subscription for a different URL.",
        ["Dlg_SubscriptionUrl"] = "Subscription URL",
        ["UpdateFetchUrl"] = "Update the fetch URL",
        ["BuiltInCannotRemove"] = "This list ships with KVN and cannot be removed. Uncheck it to take its servers out of use.",
        ["Dlg_RemoveSubscription"] = "Remove subscription",
        ["RemoveSubscriptionBody"] = "Remove \"{0}\" and the {1} server(s) it provided?",
        ["Updating"] = "Updating {0}...",
        ["Dlg_UpdateFailed"] = "Subscription update failed",
        ["Dlg_SomeFailed"] = "Some subscriptions failed",
        ["Never"] = "never",
        ["Deactivated"] = "Deactivated",
        ["QuotaOf"] = "{0} of {1}",
        ["Expires"] = "expires {0}",

        // routing
        ["NewRule"] = "New rule",
        ["Dlg_ResetRouting"] = "Reset routing",
        ["ResetRoutingBody"] = "Discard all rules and restore the defaults?",
        ["DomainsCount"] = "{0} domain(s)",
        ["IpRulesCount"] = "{0} IP rule(s)",
        ["PortsList"] = "ports {0}",
        ["ProcessesCount"] = "{0} process(es)",
        ["MatchesNothing"] = "matches nothing yet",

        // server rows
        ["Row_Timeout"] = "timeout",
        ["Row_Resting"] = "resting",
        ["Row_Fail"] = "{0} fail",
        ["Row_Untried"] = "untried",
        ["Row_Reliable"] = "reliable",
        ["Row_NoRecord"] = "No record yet. Filled in once this server has actually carried traffic.",
        ["Row_OkFailed"] = "{0} ok, {1} failed",
        ["Row_Typical"] = "{0} ms typical",
        ["Row_Jitter"] = "{0} ms jitter",
        ["Row_RestingAfter"] = "resting after repeated failures",
        ["Row_LastError"] = "last error: {0}",

        // editor
        ["Editor_AddServer"] = "Add server",
        ["Editor_EditServer"] = "Edit server",
        ["Editor_LinkNotParsed"] = "Link could not be parsed.",
        ["Editor_ReadyToSave"] = "Ready to save.",
        ["Editor_FixFirst"] = "Fix these first",

        // tray and dialogs
        ["Tray_ShowWindow"] = "Show window",
        ["Tray_Exit"] = "Exit",
        ["Tray_ConnectedTo"] = "Connected — {0}",
        ["Tray_Connecting"] = "Connecting...",
        ["Tray_Stopping"] = "Stopping...",
        ["Msg_Yes"] = "Yes",
        ["Msg_No"] = "No",
        ["Crash"] = "KVN hit an unexpected error",
    };
}
